### ISSUE TITLE
Compatibility php > 7.0

### ISSUE THREAD

**Issue by vinise** [zendframework/zend-json#19]
check requirement to match 7.0.*

**Comment by Ocramius** [comment]
[Already supported](https://github.com/zendframework/zend-json/blob/8a3d2905b3f7d3d5c50958adc4195b5b099c6427/composer.json#L17)

**Comment by vinise** [comment]
zendframework/zend-json 2.6.1 requires php ^5.5 || ^7.0 -> your PHP version (7.0.3) in composer.json does not satisfy that requirement.

Really strange :/

**Comment by gianarb** [comment]
Can you paste your composer output please :)

**Comment by vinise** [comment]
Actually it's working when direct require! (so sorry for the issue)
But this project https://github.com/marcaube/ObHighchartsBundle/blob/master/composer.json
require "zendframework/zend-json": "~2.3" ==> so inclunding 2.6.1 (with php ^5.5 || ^7.0)
but then if fail :/
==> http://pastebin.com/ZavRKk9F
don't think its an error from your side but if you have any idea (not blocking at all)
Thanks :)
