### ISSUE TITLE
sql query on encoded json

### ISSUE THREAD

**Issue by ozinal** [zendframework/zend-json#32]
Having issue when query the column contains encoded data however sql query below works fine for encoded data by json_encode func,

Query
`SELECT * FROM bidtaxi_master.errorlog WHERE `Info` IS NOT NULL and
    JSON_EXTRACT(Resource, "$.env\'") = "sandbox\'";`

Is there any other sql statement I can use for json query encoded by this component or doctrine?

**Comment by Ocramius** [comment]
This has nothing to do with zend-json, zend-db or doctrine: this depends on your RDBMS (mysql?). You should probably ask about it on stackoverflow...

Closing as `invalid`.
