### ISSUE TITLE
Why the public properties aren't get retreived and encoded?

### ISSUE THREAD

**Issue by razcakappa** [zendframework/zend-json#36]
I have a code like this.

`$customer= $this->entityManager->getRepository(Customer::class)->findOneById('5');
$jsonObject = \Zend\Json\Json::encode($customer,true);
print_r($jsonObject);
die;`

However the output becomes empty/nothing. No errors either from PHP or the ZF3
I can assure, all the data properties of `Class Customer` are set to `public`.
Where would be the problem?

**Comment by samsonasik** [comment]
You may need to pass `array` instead of customer object. If you want to pass object to `Json::encode()`, the object need to have `toJson` or `toArray` method. For your use case, you may need to cast the `Customer` instance to array first, like the following : 

```php
use Zend\Json\Json;

$arrayCustomer = (array) $customer;
$jsonObject = Json::encode($arrayCustomer, true); 
print_r($jsonObject); die;
```
