### ISSUE TITLE
URL to licence is 404ing

### ISSUE THREAD

**Issue by localheinz** [zendframework/zend-json#40]
An attempt to retrieve https://framework.zend.com/license/new-bsd results in

![screen shot 2018-01-02 at 12 17 02](https://user-images.githubusercontent.com/605483/34482184-bf7c4580-efb6-11e7-9a9d-737f7f9bc8e5.png)

**Comment by Xerkus** [comment]
I assume you mean the link in docheaders. It needs to be changed to point to the repo itself.
Template is 
```
/**
 * @see       https://github.com/{org}/{repo} for the canonical source repository
 * @copyright Copyright (c) {year} Zend Technologies USA Inc. (http://www.zend.com)
 * @license   https://github.com/{org}/{repo}/blob/master/LICENSE.md New BSD License
 */
```
