### ISSUE TITLE
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by matbech** [zendframework/zend-json#45]
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in zendframework\zend-json\src\Decoder.php on line 110
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in zendframework\zend-json\src\Decoder.php on line 365
etc

**Comment by yosoyhendrix** [comment]
thank you very much to me I was able to replace this $chrs{$i} hear this $chrs[$i]
fuente [https://github.com/webimpress/zend-json/commit/205e0a84e94d306bd9ef31cc20dff5fc01095068](url)
